# Site settings
title: Otoll
url: www.otoll.org

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Otoll

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/shafatrahman0
  - title: linkedin
    url: https://www.linkedin.com/in/shadman-rahman-688139125/

# Build settings
markdown: kramdown
permalink: pretty
